[package]
name = "sysy_compiler-rs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
chrono = "0.4.38"
koopa = "0.0.7"
lalrpop-util = { version = "0.20.2", features = ["lexer"] }
